FROM localhost/emacs-base

RUN dnf in -y go

ENV GOPATH=/var/local/go
ENV PATH=$PATH:/var/local/go/bin

RUN go install golang.org/x/tools/gopls@latest

COPY golang-config.el /var/local/
RUN echo "(load \"/var/local/golang-config.el\")" >> /var/local/init.el

