FROM localhost/emacs-base

RUN yum install python3-tkinter

RUN pip install 'python-lsp-server[all]' \
    pyls-flake8 pylsp-mypy pyls-isort python-lsp-black pyls-memestra pylsp-rope \
    matplotlib

COPY python-config.el /var/local/

RUN echo "(load \"/var/local/python-config.el\")" >> /var/local/init.el